package com.sevam.core.common.model

object SevamSampleData {
    val banners = listOf(
        PromoBanner(
            id = "same-day",
            locationLabel = "Koramangala, Bangalore",
            title = "Same-Day Service, Guaranteed",
            subtitle = "Book before noon and get a verified professional at your doorstep today.",
            primaryAction = "Browse Services",
            secondaryAction = "View All Services",
            highlights = listOf("Verified Pros", "4.8+ Rated", "60-min Response"),
        ),
        PromoBanner(
            id = "weekend",
            locationLabel = "HSR Layout, Bangalore",
            title = "Weekend Home Reset",
            subtitle = "Deep cleaning, appliance repair, and grooming offers bundled for busy households.",
            primaryAction = "Explore Deals",
            secondaryAction = "Book Again",
            highlights = listOf("Up to 50% Off", "Instant Slots", "No Hidden Fees"),
        ),
    )

    val categories = listOf(
        ServiceCategory("all", "All", 39),
        ServiceCategory("electrical", "Electrical", 7),
        ServiceCategory("plumbing", "Plumbing", 9),
        ServiceCategory("cleaning", "Cleaning", 12),
        ServiceCategory("cooking", "Chef", 6),
        ServiceCategory("carpentry", "Carpentry", 5),
        ServiceCategory("pest", "Pest Control", 4),
        ServiceCategory("grooming", "Grooming", 15),
        ServiceCategory("labour", "Labour", 8),
        ServiceCategory("appliance", "Appliance Repair", 6),
    )

    val services = listOf(
        ServiceItem(
            id = "svc-ac-repair",
            categoryId = "appliance",
            name = "AC Service & Repair",
            description = "Cooling issue diagnosis, deep clean, gas pressure check, and minor repair support.",
            durationLabel = "1 hr",
            price = 499,
            originalPrice = 899,
            rating = 4.8,
            reviewCount = 280,
            imageUrl = "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=900&q=80",
            badge = "44% OFF",
            processSteps = listOf("Inspect unit", "Clean filters and coils", "Check cooling performance", "Share job summary"),
        ),
        ServiceItem(
            id = "svc-home-cleaning",
            categoryId = "cleaning",
            name = "Deep Home Cleaning",
            description = "Full-home deep clean for kitchen, bathroom, bedroom, and living spaces.",
            durationLabel = "2 hrs",
            price = 399,
            originalPrice = 799,
            rating = 4.7,
            reviewCount = 340,
            imageUrl = "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=900&q=80",
            badge = "50% OFF",
            processSteps = listOf("Walkthrough and checklist", "Deep cleaning and sanitization", "Final touch-up", "Completion review"),
        ),
        ServiceItem(
            id = "svc-salon",
            categoryId = "grooming",
            name = "Hair Styling at Home",
            description = "Salon-quality haircut, styling, and finishing by trained beauty professionals.",
            durationLabel = "1.5 hrs",
            price = 599,
            originalPrice = 1199,
            rating = 4.8,
            reviewCount = 256,
            imageUrl = "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=900&q=80",
            badge = "50% OFF",
            processSteps = listOf("Style consultation", "Prep and section", "Cut or styling service", "Clean-up and final look"),
        ),
        ServiceItem(
            id = "svc-pest",
            categoryId = "pest",
            name = "Pest Control Service",
            description = "Targeted pest treatment for kitchens, bathrooms, and common infestation zones.",
            durationLabel = "45 mins",
            price = 299,
            originalPrice = 599,
            rating = 4.7,
            reviewCount = 198,
            imageUrl = "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80",
            badge = "50% OFF",
            processSteps = listOf("Infestation assessment", "Safe chemical application", "Coverage confirmation", "After-care guidance"),
        ),
        ServiceItem(
            id = "svc-wiring",
            categoryId = "electrical",
            name = "Wiring Installation",
            description = "New wiring setup, switchboard fixes, and safety inspection for home circuits.",
            durationLabel = "2 hrs",
            price = 299,
            originalPrice = null,
            rating = 4.6,
            reviewCount = 142,
            imageUrl = "https://images.unsplash.com/photo-1565008447742-97f6f38c985c?auto=format&fit=crop&w=900&q=80",
            processSteps = listOf("Inspection", "Material confirmation", "Installation and testing", "Safety handover"),
        ),
        ServiceItem(
            id = "svc-fan",
            categoryId = "electrical",
            name = "Fan Installation",
            description = "Ceiling fan installation, mounting, balancing, and electrical fitment.",
            durationLabel = "1 hr",
            price = 199,
            originalPrice = 399,
            rating = 4.5,
            reviewCount = 96,
            imageUrl = "https://images.unsplash.com/photo-1615874959474-d609969a20ed?auto=format&fit=crop&w=900&q=80",
            badge = "50% OFF",
            processSteps = listOf("Mounting check", "Installation", "Balancing and fitment", "Test run"),
        ),
        ServiceItem(
            id = "svc-plumbing",
            categoryId = "plumbing",
            name = "Pipe Repair",
            description = "Leak detection, joint repair, and replacement support for visible household pipework.",
            durationLabel = "1 hr",
            price = 199,
            originalPrice = null,
            rating = 4.5,
            reviewCount = 171,
            imageUrl = "https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=900&q=80",
            processSteps = listOf("Leak diagnosis", "Repair or seal", "Pressure check", "Area cleanup"),
        ),
        ServiceItem(
            id = "svc-tank",
            categoryId = "plumbing",
            name = "Water Tank Cleaning",
            description = "Overhead tank descaling, sludge removal, wash, and sanitization.",
            durationLabel = "2 hrs",
            price = 599,
            originalPrice = null,
            rating = 4.6,
            reviewCount = 109,
            imageUrl = "https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?auto=format&fit=crop&w=900&q=80",
            processSteps = listOf("Drain and scrub", "High-pressure rinse", "Disinfection", "Refill guidance"),
        ),
        ServiceItem(
            id = "svc-chef",
            categoryId = "cooking",
            name = "Daily Home Cook",
            description = "Experienced home chef for daily meal prep, North or South Indian preferences, and tiffin routines.",
            durationLabel = "3 hrs",
            price = 799,
            originalPrice = null,
            rating = 4.9,
            reviewCount = 84,
            imageUrl = "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=900&q=80",
            processSteps = listOf("Menu planning", "Ingredient check", "Cooking session", "Kitchen wrap-up"),
        ),
        ServiceItem(
            id = "svc-labour",
            categoryId = "labour",
            name = "House Shifting Helper",
            description = "Reliable labour support for loading, unloading, and room-to-room household shifting.",
            durationLabel = "4 hrs",
            price = 699,
            originalPrice = null,
            rating = 4.4,
            reviewCount = 67,
            imageUrl = "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80",
            processSteps = listOf("Scope review", "Packing assist", "Move support", "Final placement"),
        ),
    )

    val addresses = listOf(
        Address(
            id = "addr-home",
            label = "Home",
            line1 = "A-204, Skyline Apartments",
            line2 = "Koramangala 5th Block",
            city = "Bangalore 560034",
            isDefault = true,
        ),
        Address(
            id = "addr-office",
            label = "Office",
            line1 = "42, 7th Main Road",
            line2 = "HSR Layout Sector 2",
            city = "Bangalore 560102",
        ),
        Address(
            id = "addr-other",
            label = "Parents",
            line1 = "18, Residency Lane",
            line2 = "Indiranagar",
            city = "Bangalore 560038",
        ),
    )

    val worker = WorkerProfile(
        id = "worker-rajesh",
        name = "Rajesh Kumar",
        role = "Senior AC Technician",
        rating = 4.8,
        completedJobs = 342,
        isVerified = true,
        phoneNumber = "+91 98765 43210",
        avatarUrl = "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
    )

    val bookings = listOf(
        Booking(
            id = "booking-active",
            stage = BookingStage.ACTIVE,
            service = services.first { it.id == "svc-ac-repair" },
            dateLabel = "Today",
            timeLabel = "2:30 PM",
            address = addresses.first(),
            paymentMethod = "UPI",
            totalAmount = 617,
            bookingReference = "SVM-20845",
            statusLabel = "In Progress",
            etaLabel = "~25 mins remaining",
            supportHint = "Our support team is available 24/7 to assist with this booking.",
            worker = worker,
            steps = listOf(
                BookingStep("Confirmed", BookingStepState.COMPLETE),
                BookingStep("En Route", BookingStepState.COMPLETE),
                BookingStep("Arrived", BookingStepState.CURRENT),
                BookingStep("In Progress", BookingStepState.UPCOMING),
                BookingStep("Done", BookingStepState.UPCOMING),
            ),
        ),
        Booking(
            id = "booking-upcoming-1",
            stage = BookingStage.UPCOMING,
            service = services.first { it.id == "svc-home-cleaning" },
            dateLabel = "Tomorrow",
            timeLabel = "10:00 AM",
            address = addresses.first(),
            paymentMethod = "Card",
            totalAmount = 449,
            bookingReference = "SVM-20812",
            statusLabel = "Scheduled",
            etaLabel = "Starts in 19 hrs",
        ),
        Booking(
            id = "booking-upcoming-2",
            stage = BookingStage.UPCOMING,
            service = services.first { it.id == "svc-chef" },
            dateLabel = "Wed, 30 Apr",
            timeLabel = "7:30 AM",
            address = addresses[1],
            paymentMethod = "Wallet",
            totalAmount = 799,
            bookingReference = "SVM-20814",
            statusLabel = "Scheduled",
            etaLabel = "Starts in 2 days",
        ),
        Booking(
            id = "booking-past-1",
            stage = BookingStage.PAST,
            service = services.first { it.id == "svc-home-cleaning" },
            dateLabel = "Completed on 28 Feb 2026",
            timeLabel = "11:30 AM",
            address = addresses.first(),
            paymentMethod = "UPI",
            totalAmount = 299,
            bookingReference = "SVM-20112",
            statusLabel = "Completed",
        ),
        Booking(
            id = "booking-past-2",
            stage = BookingStage.PAST,
            service = services.first { it.id == "svc-salon" },
            dateLabel = "Completed on 15 Feb 2026",
            timeLabel = "4:00 PM",
            address = addresses.first(),
            paymentMethod = "Card",
            totalAmount = 599,
            bookingReference = "SVM-19880",
            statusLabel = "Completed",
        ),
    )

    val paymentMethods = listOf(
        PaymentMethod("upi", "UPI", "Pay with any UPI app", isDefault = true),
        PaymentMethod("card", "Credit / Debit Card", "Visa ending in 4210"),
        PaymentMethod("wallet", "Sevam Wallet", "Balance available", isLive = false),
    )

    val walletSummary = WalletSummary(
        balance = 1250,
        isLive = false,
        historyPreview = listOf("Wallet launch pending backend contract", "Top-up and history will appear here"),
    )

    val userProfile = UserProfile(
        name = "Nikhil Sharma",
        email = "nikhil.sharma@gmail.com",
        phoneNumber = "+91 98765 43210",
        dateOfBirth = "14 August 1995",
        gender = "Male",
        memberSince = "Jan 2024",
        referralCode = "NIKHIL40",
    )

    val notifications = listOf(
        NotificationItem(
            id = "notif-1",
            title = "Rajesh Kumar is on the way",
            body = "Your AC service professional will arrive in about 25 minutes.",
            timeLabel = "2 mins ago",
            isUnread = true,
            bookingId = "booking-active",
        ),
        NotificationItem(
            id = "notif-2",
            title = "Weekend deep cleaning deal is live",
            body = "Save up to Rs 400 on deep home cleaning bookings this week.",
            timeLabel = "1 hr ago",
            isUnread = true,
        ),
        NotificationItem(
            id = "notif-3",
            title = "Booking completed successfully",
            body = "Thanks for choosing Sevam. Rate your last service to help others.",
            timeLabel = "Yesterday",
            isUnread = false,
            bookingId = "booking-past-1",
        ),
    )

    val recentSearches = listOf(
        SearchSuggestion("search-ac", "AC repair"),
        SearchSuggestion("search-bathroom", "Bathroom cleaning"),
        SearchSuggestion("search-cook", "Home cook"),
    )

    val trustHighlights = listOf(
        "Background-checked professionals",
        "Transparent pricing before booking",
        "Cashless payments and support",
    )
}
